---
# tasks file for ansible-role-sysadmindays
- name: Load distribution specific vars
  include_vars:
    file: "vars/{{ ansible_distribution }}.yml"
- name: CentOS - Activate EPEL
  yum:
    name: epel-release
    state: present
  when: ansible_distribution == "CentOS"
- name: CentOS - Install nginx
  yum:
    name: nginx
    state: present
  when: ansible_distribution == "CentOS"
- name: Debian - Install nginx
  apt:
    name: nginx
    state: present
    update_cache: yes
  when: ansible_distribution == "Debian"
- name: CentOS - Create missing folders
  file:
    path: "{{ nginx_default_vhost_path }}"
    state: directory
  when: ansible_distribution == "CentOS"
- name: Deploy codebase
  copy:
    src: files/codebase.html
    dest: "{{ nginx_default_vhost_path }}/index.html"
- name: Ensure nginx is started
  systemd:
    name: nginx
    state: started
